---
title: "p8105_HW1"
author: "Sania Sheifuddin"
date: "2026-09-23"
output: github_document
---

#Loading libraries for this experiement 

```{r}
library(tidyverse)
```
# The data in this dataset, including names / values of important variables
```{r}
install.packages("palmerpenguins")
```

```{r}
data("penguins", package = "palmerpenguins")
```

```{r}
names (penguins)
penguins = janitor::clean_names(penguins)
```

```{r}
penguins
```

```{r}
skimr::skim(penguins)
```

# The size of the data set (using nrow and ncol)

```{r}
penguins
nrow(penguins)
ncol(penguins)
```
```{r}
round(mean(penguins$flipper_length_mm, na.rm = TRUE), 1)
```

```{r }
library (tidyverse) 
flipper_bill_plot =
  ggplot (penguins, aes(x = bill_length_mm, 
                        y = flipper_length_mm, color = species)) +
  geom_point()

flipper_bill_plot

ggsave("flipper_bill_plot.pdf")
```

```{r}
penguins_df = tibble (
  norm_samp = rnorm(10, mean = 1),
  norm_samp_pos = norm_samp > 0, 
  vec_char = c ("My", "name", "is", "Sania", "and", "I", "am", "in", "epi", "department"),
  vec_factor = factor(c("a","b","c","a","b","c","a","b","c","a"))
)
```

```{r}
mean(pull(penguins_df, norm_samp))
mean(pull(penguins_df,norm_samp_pos))
mean(pull(penguins_df, vec_char))
mean(pull(penguins_df, vec_factor))
```

```{r}
as.numeric(pull(penguins_df,norm_samp))
as.numeric(pull(penguins_df,norm_samp_pos))
as.numeric(pull(penguins_df, vec_char))
as.numeric(pull(penguins_df, vec_factor))
```

